apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-{{ .Values.clientService.name }}
              servicePort: 3000
          - path: /api/
            backend:
              serviceName: {{ .Release.Name }}-{{ .Values.serverService.name }}
              servicePort: 5000