apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-{{ .Values.serverService.name }}
spec:
    type: {{ .Values.serverService.type }}
    selector:
        component: server
    ports:
        - port: {{ .Values.serverService.port }}
          targetPort: {{ .Values.serverService.targetPort }}